if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("ChAMP")
library("ChAMP")
library(ChAMPdata)
BiocManager::install("ChAMPdata")
library(ChAMPdata)
"ChAMPdata" %in% rownames(installed.packages())
testDir=system.file("extdata",package="ChAMPdata")
BiocManager::install("ChAMPdata")
options(timeout = 5000)
.libPaths()
tempdir()
packageVersion("ChAMP")
library(ChAMP)
packageDescription("ChAMP")[c("Version", "Depends", "Imports")]
